modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"

[[mods]]
modId = "tacz_mechanics"
version = "0.1.0"
displayName = "TaCZ Mechanics"
displayURL = "https://discord.gg/gV3jYaEtDa"
authors = "Liko"
description = '''Adds a plethora of mechanics to TaCZ'''

[[mixins]]
config = "tacz_mechanics.mixins.json"

[[dependencies."tacz_mechanics"]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."tacz_mechanics"]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies."tacz_mechanics"]]
modId = "veil"
type = "optional"
versionRange = "[3.3.0,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies."tacz_mechanics"]]
modId = "snassets"
type = "required"
versionRange = "[1.0.0,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies."tacz_mechanics"]]
modId = "snassets_particles"
type = "required"
versionRange = "[1.0.0,)"
ordering = "NONE"
side = "CLIENT"
